spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017

api:
  private-hostname: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env
